### ISSUE TITLE
Is it even possible to reduce the size further?

### ISSUE THREAD

**Issue by dl-tg** [donno2048/snake#16]
I have been experimenting for hours and it either stays at 85 or wrecks up the game. Is it possible to go further? IMO, the only way is to compromise functionality. Either way, the result is already impressive.

**Comment by donno2048** [comment]
@RolfRolles someone said you might be able to do it, would really appreciate it if you take a look

**Comment by znakeeye** [comment]
Please comment the asm code.

**Comment by donno2048** [comment]
> Please comment the asm code.

I don't have time to do it, will try doing it on Sunday

**Comment by donno2048** [comment]
commented now 😀

**Comment by donno2048** [comment]
Maybe @JohnHammond too

**Comment by donno2048** [comment]
@HellMood

**Comment by donno2048** [comment]
@runestubbe
