### ISSUE TITLE
Problem In Rendering

### ISSUE THREAD

**Issue by farzadso** [donno2048/snake#17]
Hi,

The characters don't seem to render correctly for me in the browser.

This is what I see when I open the demo link:

![image](https://github.com/donno2048/snake/assets/19854715/63ff5c89-d4c9-4950-8c97-0e395220cbd9)

Let me know if you need any more information for debugging it.

**Comment by donno2048** [comment]
The characters used to be ○ for snake body parts and ● for the food but then I decided to use the characters themselves to store data (this is not accurate you can read the code to understand exactly what I mean, I intend on commenting it tomorrow, I wanted to do it today but I had an unexpected event...)
